from setuptools import setup, find_packages

setup(
    name='TelegramSendMessage',
    version='2.1.0',
    author='JeremyDang',
    author_email='itminhdp@gmail.com',
    description='Telegram BOT có chức năng nhận tin nhắn sau đó chuyển tiếp tin nhắn đến các Channel do BOT quản lý.',
    long_description=open('README.md').read(),
    long_description_content_type='text/markdown',
    url='https://github.com/MinhIT9',
    packages=find_packages(),
    install_requires=[
        'aiohttp==3.9.3',
        'aiosignal==1.3.1',
        'anyio==4.3.0',
        'attrs==23.2.0',
        'certifi==2024.2.2',
        'charset-normalizer==3.3.2',
        'frozenlist==1.4.1',
        'h11==0.14.0',
        'httpcore==1.0.4',
        'httpx==0.27.0',
        'idna==3.6',
        'multidict==6.0.5',
        'python-telegram-bot==21.0.1',
        'requests==2.31.0',
        'sniffio==1.3.1',
        'urllib3==2.2.1',
        'yarl==1.9.4',
    ],
    classifiers=[
        'Programming Language :: Python :: 3',
        'License :: OSI Approved :: MIT License',
        'Operating System :: OS Independent',
    ],
    python_requires='>=3.6',
)
